version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.11
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      network_100:
      network_200:
      network_222:
      services_network:

  client_1:
    build:
      context: ./nodes/Client_1
    container_name: client_1
    environment:
      - NODE_NAME=NODE1
      - MQTT_BROKER=mqtt://mosquitto
      - MQTT_PORT=1883
      - PORT=3001
      - MQTT_TOPIC_TO_PUBLISH=temperature
      - MQTT_TOPIC_TO_LISTEN=temperature
      - TEMPERATURE_INTERVAL=5000
    depends_on:
      - mosquitto
    networks:
      network_100:
        ipv4_address: 192.168.100.100

  client_2:
    build:
      context: ./nodes/Client_2
    container_name: client_2
    environment:
      - NODE_NAME=NODE2
      - MQTT_BROKER=mqtt://mosquitto
      - MQTT_PORT=1883
      - PORT=3002
      - MQTT_TOPIC_TO_PUBLISH=temperature
      - MQTT_TOPIC_TO_LISTEN=temperature
      - TEMPERATURE_INTERVAL=8000
    depends_on:
      - mosquitto
    networks:
      network_200:
        ipv4_address: 192.168.200.200

  client_3:
    build:
      context: ./nodes/Client_3
    container_name: client_3
    environment:
      - NODE_NAME=NODE3
      - MQTT_BROKER=mqtt://mosquitto
      - MQTT_PORT=1883
      - PORT=3003
      - MQTT_TOPIC_TO_PUBLISH=temperature
      - TEMPERATURE_INTERVAL=10000
    depends_on:
      - mosquitto
    networks:
      network_222:
        ipv4_address: 192.168.222.222
  
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./nodes/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
    networks:
      services_network:
        ipv4_address: 192.168.15.100

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdbv2:/root/.influxdbv2
    networks:
      services_network:
        ipv4_address: 192.168.15.101
      ui_network:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      ui_network:
        ipv4_address: 192.168.16.100

networks:
  network_100:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  network_200:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24
  network_222:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.222.0/24
  services_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.15.0/24
  ui_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.16.0/24

volumes:
  grafana-storage:
  influxdbv2:
